CREATE TABLE IF NOT EXISTS users(
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar,
                                    email varchar,
                                    login varchar,
                                    birthday date
);

CREATE TABLE IF NOT EXISTS films(
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar,
                                    description varchar,
                                    release_date date,
                                    duration integer,
                                    rating varchar
);

CREATE TABLE IF NOT EXISTS friendship(
                                         id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         user_id integer REFERENCES users (id),
                                         follower_id integer REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS genre(
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    film_id integer REFERENCES films (id),
                                    genre varchar
);

CREATE TABLE IF NOT EXISTS likes(
                                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id integer REFERENCES users (id),
                                    film_id integer REFERENCES films (id)
);